title: arnau diaz
email: diazarnau0@gmail.com
description: ( epokhē )
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.arnaudiaz.com/"
github_username:  vrnvu

permalink: /:slug.html

favicon: "./favicon.ico" # relative path to site's favicon
# goat_counter: "riggraz" # put your GoatCounter name if you want to use GoatCounter analytics

# Build settings
remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
